image

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,7 +30,7 @@ jobs:
           command: |
             source $BASH_ENV
             echo 'Build docker with ' $NODE_VERSION
-            docker pull microbox/node:$NODE_VERSION
+            docker pull microbox/node:$NODE_VERSION || echo 'image not found'
             if [[ "$(docker images -q microbox/node:$NODE_VERSION 2> /dev/null)" == "" ]]; then
               docker build -t microbox/node:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .
               echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
